name: PBIX Docs

on:
  workflow_dispatch:
  push:
    paths:
      - '.extract/**'
      - 'models/**'
      - 'tools/**'
      - '.github/workflows/pbix-docs.yml'

permissions:
  contents: write

jobs:
  docs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Markdown for all models
        shell: pwsh
        run: |
          mkdir docs 2>$null
          # Najdi všechny zdrojové modely (PbixProj/TMDL)
          $modelFiles = Get-ChildItem -Recurse -Include model.bim,model.tmsl.json
          if ($modelFiles.Count -eq 0) {
            Write-Error "Nenalezen žádný model (model.bim ani model.tmsl.json). \
            Proveď lokálně 'pbi-tools extract <*.pbix> -o ./models/<název> --include-m' a commitni složku."
          }
          foreach ($m in $modelFiles) {
            $root = Split-Path $m.FullName -Parent
            $name = Split-Path $root -Leaf
            ./tools/Generate-ModelDocs.ps1 -ExtractRoot $root -OutFile "docs/$name.md"
          }

      - name: Commit docs back
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update PBIX docs [skip ci]" || exit 0
          git push
